# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    app_oauth.user.provider.fosub_bridge:
        class:     AppBundle\Security\Core\User\AppFOSUBUserProvider
        arguments: ['@fos_user.user_manager', { google: googleId }]